### PR TITLE
Feature/decorated stages

### PR DESCRIPTION
**Pull request by davibicudo**
Upgrading and improving DecoratedStage; plus addressing issues #61 and #51 .

### CODE REVIEW

**Review by sebhoerl — APPROVED** [review]

**Comment by davibicudo** [comment]
Ok, thanks for approving! I forgot to add a note in the changelog again... 

Something else I wanted to do was to add a section in the README on how to use the DecoratedStage, which seems to me a significant simplification of the pipeline-setup and comes close to simple everyday Python-style, improving thus the usability of synpp and the integration of the package in existing code. 

I started writing something here: 

https://github.com/eqasim-org/synpp/pull/62/files#diff-5850e7a07355acf3b3c97cb76af205ed39a64f6b30be10aa2aff11a7234e6cddR922

But before going further on this, I thought the best would be if you would test this new feature and decide if it really is as useful as I'm thinking, and in this case perhaps integrate that comment in the README in the way you think best suits you and this project.

Let me know what you think, and then we can merge this PR.

**Comment by sebhoerl** [comment]
I think it looks good, just had a look at your explanations. Yes, they could go into the main README, this looks very useful. Unfortunately I don't have the time to test it right away, but I see how it can help and if it is useful for you, I think it is fine to add it :)

**Comment by davibicudo** [comment]
Now it should be good to merge! 

By the way, any chance this can be released to pip right away? I'm using it as a dependency and installing with pip+git doesn't work so well here.

In case you want to automate it, there seems to be a straightforward way with GitHub actions: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by sebhoerl** [comment]
Thanks! Done: https://pypi.org/project/synpp/1.5.0

**Comment by davibicudo** [comment]
Great, thanks!!

**Pull request merged**
