### PR TITLE
Feature/decorated stages

### PR DESCRIPTION
**Pull request by davibicudo**
Another PR :) 
Addressing suggestion made at #57. 
I had to change the logic a little bit, just let me know if this conflicts with some other design concept you have in mind.

### CODE REVIEW

**Comment by sebhoerl** [comment]
Very nice :) Looks go to merge, just add it to the changelog.

**Review by sebhoerl — APPROVED** [review]

**Comment by davibicudo** [comment]
Nice, thanks! Was cool to work in these PRs. With the changes, perhaps would be nice to have a new tag released?

**Comment by sebhoerl** [comment]
Yes, I'll look into making a new release (always have to look up first how this works with pip).

**Comment by sebhoerl** [comment]
Done :)

**Pull request merged**
